language: ruby
branches:
  only:
  - master
rvm:
- 2.5.7
before_install: gem update --system
script: bundle exec jekyll build --future
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  on:
    branch: master
exclude: [vendor]
sudo: false
