language: ruby
branches:
  only:
  - master
rvm:
- 2.7.2
cache: bundler
before_install: gem update --system
script: bundle exec jekyll build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: _site
  on:
    branch: master
exclude: [vendor]
sudo: false
